// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetRootResourceRequest = Record<string, never>;

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RootResource } from "./RootResource";

export type GetRootResourceResponse = { resource: RootResource, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandError } from "./CommandError";

export type GetRootResourceErrors = { "type": "GenericError", "error": CommandError };

